
[package]
name = "matching-engine"
version = "0.1.0"
edition = "2024"

[dependencies]
uuid = { version = "1.23.1", features = ["v4", "v7", "serde"] }
rust_decimal = { version = "1.41.0", features = ["serde"] }
thiserror = "2.0.18"
crossbeam = "0.8.4"
derive_more = { version = "2.1.1", features = ["full"] }
rdkafka = {  version = "0.39.0", features = ["cmake-build"] }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.149"
ctrlc = "3.5.2"
tracing = "0.1.44"
tracing-subscriber = { version = "0.3.23", features = ["env-filter", "json", "fmt"] }
