spring:
  application:
    name: order-service

  datasource:
    url: jdbc:postgresql://localhost:15432/order_db
    driver-class-name: org.postgresql.Driver
    username: exchange
    password: exchange

  jooq:
    sql-dialect: POSTGRES

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      auto-offset-reset: earliest

kafka:
  listeners:
    order-outbox:
      group-id: order-outbox-status-updater
      topics:
        reserve-order: order.RESERVE_ORDER
        place-order: order.PLACE_ORDER
        cancel-order: order.CANCEL_ORDER
    engine:
      group-id: order-engine-event-handler
      topics:
        accepted: engine.ACCEPTED
        matched: engine.MATCHED
        canceled: engine.CANCELED
        rejected: engine.REJECTED
    account:
      group-id: account-event-handler
      topics:
        reserved: account.RESERVED
        rejected: account.REJECTED

management:
  tracing:
    sampling:
      probability: 1.0
  opentelemetry:
    tracing:
      export:
        otlp:
          endpoint: http://localhost:4318/v1/traces
  otlp:
    metrics:
      export:
        url: http://localhost:4318/v1/metrics

#  grpc:
#    client:
#      default-channel:
#        address: static://localhost:9090 # mock
#        negotiation-type: plaintext
