spring:
  application:
    name: account-service

  datasource:
    url: jdbc:postgresql://localhost:25432/account_db
    driver-class-name: org.postgresql.Driver
    username: exchange
    password: exchange

  jooq:
    sql-dialect: POSTGRES

  grpc:
    server:
      port: 9090

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      auto-offset-reset: earliest

kafka:
  listeners:
    account-outbox:
      group-id: account-outbox-status-updater
      topics:
        reserved: account.RESERVED
        rejected: account.REJECTED
    order:
      group-id: account-order-event-handler
      topics:
        reserve: order.RESERVE_ORDER
    engine:
      group-id: account-engine-event-handler
      topics:
        matched: engine.MATCHED
        canceled: engine.CANCELED
        rejected: engine.REJECTED