spring:
  application:
    name: account-service

  datasource:
    url: jdbc:postgresql://localhost:25432/account_db
    driver-class-name: org.postgresql.Driver
    username: exchange
    password: exchange

  jooq:
    sql-dialect: POSTGRES

  grpc:
    server:
      port: 9090